version: '3.8'

services: 
  terraform:
    build: .
    volumes: 
      - .:/workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: :${AWS_SECRET_ACCESS_KEY}
    command: ["terraform", "apply", "-auto-aprove"]
