version: '3.8'

services: 
  terraform_container:
    image: hashicorp/terraform:latest
    volumes: 
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env
    command: "apply -auto-approve"
